/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import controller.GerenciaAndar;
import controller.GerenciaQuarto;
import model.Andar;
import model.Quarto;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

public class TelaAmbientes extends javax.swing.JFrame {
    private GerenciaAndar gencAndar = new GerenciaAndar();
    private GerenciaQuarto gencQuarto = new GerenciaQuarto();
    /**
     * Creates new form AndarViewTest
     */
    public TelaAmbientes() {
        initComponents();
        gerenciaTable();
    }
    
    public void gerenciaTable(){     
        if(rbAndares.isSelected()){
            jpAndar.setVisible(true);
            jpQuarto.setVisible(false);
            btnSalvar.setEnabled(true);
            btnEditar.setEnabled(false);
            populaTabelaAndar();
        }else if(rbQuartos.isSelected()){
            jpAndar.setVisible(false);
            jpQuarto.setVisible(true);
            btnSalvar.setEnabled(false);
            btnEditar.setEnabled(true);
            populaTabelaQuarto();
        }
    }
    
    public void populaTabelaAndar(){
        DefaultTableModel modelo = (DefaultTableModel) tblAndar.getModel();
        
        modelo.setNumRows(0);
        
        for(Andar a: gencAndar.buscTodosAndares()){
            modelo.addRow(new Object[]{
                a.getIdAndar(),
                a.getNumAndar(),
                a.getFuncionario().getNomeFuncionario()
            });
        }
        
    }
    
    public void populaTabelaQuarto(){
        DefaultTableModel modelo = (DefaultTableModel) tblQuarto.getModel();
        
        modelo.setNumRows(0);
        
        for(Quarto q: gencQuarto.buscTodosQuartos()){
            modelo.addRow(new Object[]{
                q.getIdQuarto(),
                q.getNumQuarto(),
                q.getTipoQuarto(),
                q.getNumCamasQuarto(),
                q.getQtdBanheirosQuarto(),
                q.getDescricaoQuarto(),
                q.getContatoQuarto(),
                q.getAndar().getNumAndar()
            });
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        cbxAndar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxQuarto = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        rbAndares = new javax.swing.JRadioButton();
        rbQuartos = new javax.swing.JRadioButton();
        jpAndar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAndar = new javax.swing.JTable();
        jpQuarto = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQuarto = new javax.swing.JTable();
        btnInfos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Andar :");

        cbxAndar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cbxAndar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", " " }));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Quantidade Quartos :");

        cbxQuarto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cbxQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", " " }));

        btnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbAndares);
        rbAndares.setSelected(true);
        rbAndares.setText("Gerenciar Andar");
        rbAndares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAndaresActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbQuartos);
        rbQuartos.setText("Gerenciar Quartos");
        rbQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbQuartosActionPerformed(evt);
            }
        });

        tblAndar.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        tblAndar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Andar", "Número do Andar", "ID Funionário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAndar);

        javax.swing.GroupLayout jpAndarLayout = new javax.swing.GroupLayout(jpAndar);
        jpAndar.setLayout(jpAndarLayout);
        jpAndarLayout.setHorizontalGroup(
            jpAndarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jpAndarLayout.setVerticalGroup(
            jpAndarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAndarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblQuarto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Número Quarto", "Tipo", "Camas", "Banheiros", "Descrição", "Contato", "Andar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblQuarto);

        javax.swing.GroupLayout jpQuartoLayout = new javax.swing.GroupLayout(jpQuarto);
        jpQuarto.setLayout(jpQuartoLayout);
        jpQuartoLayout.setHorizontalGroup(
            jpQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        jpQuartoLayout.setVerticalGroup(
            jpQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        btnInfos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnInfos.setText("Informações dos Quartos");
        btnInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel1.setText("Ambiente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rbAndares)
                        .addGap(586, 586, 586)
                        .addComponent(rbQuartos))
                    .addComponent(jpAndar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInfos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxAndar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(415, 415, 415))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbxQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnInfos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAndares)
                    .addComponent(rbQuartos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAndar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jpQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(946, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //EditarAndar criação de Andar
        gencAndar.criarNewAndar(Integer.parseInt(cbxAndar.getSelectedItem().toString()),Integer.parseInt(cbxQuarto.getSelectedItem().toString()));
        gerenciaTable();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(rbAndares.isSelected()){
            if(tblAndar.getSelectedRow() != -1){
                Andar andar = new Andar();
                andar.setNumAndar(Integer.parseInt(String.valueOf(tblAndar.getValueAt(tblAndar.getSelectedRow(), 1))));
                gencAndar.excluirAndar(andar.getNumAndar());
                gerenciaTable();
            }else{
                JOptionPane.showMessageDialog(null,"Selecione um andar para excluir.");
            }
        }else if(rbQuartos.isSelected()){
            if(tblQuarto.getSelectedRow() != -1){
                Quarto quarto = new Quarto();
                quarto.setIdQuarto(Integer.parseInt(String.valueOf(tblQuarto.getValueAt(tblQuarto.getSelectedRow(), 0))));
                gencQuarto.excluirQuarto(quarto.getIdQuarto());
                gerenciaTable();
            }else{
                JOptionPane.showMessageDialog(null,"Selecione um andar para excluir.");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        if(tblQuarto.getSelectedRow() != -1){
            Quarto quarto = new Quarto();
            quarto.setIdQuarto(Integer.parseInt(String.valueOf(tblQuarto.getValueAt(tblQuarto.getSelectedRow(), 0))));
            quarto.setNumQuarto(Integer.parseInt(String.valueOf(tblQuarto.getValueAt(tblQuarto.getSelectedRow(), 1))));
            quarto.setTipoQuarto(String.valueOf(tblQuarto.getValueAt(tblQuarto.getSelectedRow(), 2)));
            quarto.setNumCamasQuarto(Integer.parseInt(String.valueOf(tblQuarto.getValueAt(tblQuarto.getSelectedRow(), 3))));
            quarto.setQtdBanheirosQuarto(Integer.parseInt(String.valueOf(tblQuarto.getValueAt(tblQuarto.getSelectedRow(), 4))));
            quarto.setDescricaoQuarto(String.valueOf(tblQuarto.getValueAt(tblQuarto.getSelectedRow(), 5)));
            quarto.setContatoQuarto(Integer.parseInt(String.valueOf(tblQuarto.getValueAt(tblQuarto.getSelectedRow(), 6))));
            quarto.setAndar(gencAndar.buscarAndar(Integer.parseInt(String.valueOf(tblQuarto.getValueAt(tblQuarto.getSelectedRow(), 7)))));
            TelaEditarQuarto qtView = new TelaEditarQuarto();
            qtView.populaCampos(quarto);
            qtView.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Selecione um andar para editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void rbAndaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAndaresActionPerformed
        gerenciaTable();
    }//GEN-LAST:event_rbAndaresActionPerformed

    private void rbQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbQuartosActionPerformed
        gerenciaTable();
    }//GEN-LAST:event_rbQuartosActionPerformed

    private void btnInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfosActionPerformed
        InformacaoQuartoView infoQView = new InformacaoQuartoView();
        infoQView.setVisible(true);
        
    }//GEN-LAST:event_btnInfosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAmbientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAmbientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAmbientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAmbientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaAmbientes tlAmb = new TelaAmbientes();
                //Define o que acontece ao clicar em fechar
                tlAmb.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                
                tlAmb.addWindowListener(new WindowAdapter(){
                    public void windowClosing(WindowEvent evt){
                        //TelaPrincipal tlPrinc = new TelaPrincipal();
                        //tlPrinc.setVisible(true);
                        tlAmb.dispose();
                    }
                });
                
                tlAmb.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInfos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxAndar;
    private javax.swing.JComboBox<String> cbxQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpAndar;
    private javax.swing.JPanel jpQuarto;
    private javax.swing.JRadioButton rbAndares;
    private javax.swing.JRadioButton rbQuartos;
    private javax.swing.JTable tblAndar;
    private javax.swing.JTable tblQuarto;
    // End of variables declaration//GEN-END:variables
}
